### PR TITLE
feat: populate GaxiosResponse with raw response information (res.url)

### PR DESCRIPTION
**Pull request by marapper**
To resolve https://github.com/googleapis/gaxios/issues/187

Adding `request.responseUrl` with real URL after redirects to response.

```
await axios.get('/redirect')

{
 config: {
   url: '/redirect',
   ...
 },
 request: {
   responseURL: 'https://example.com/real_page',
 }
}
```

### CODE REVIEW

**Comment by marapper** [comment]
@googlebot I signed it!

**Comment by marapper** [comment]
@googlebot I fixed it.

**Comment by bcoe** [comment]
@marapper don't worry about the license header, not your issue; thanks for the patch.

**Comment by marapper** [comment]
Yes, I just forgot to remove it. In axios it is populating twice but I think it's redundant.

**Comment by marapper** [comment]
@googlebot I fixed it.

**Comment by bcoe** [comment]
@marapper thank you for the contribution \o/ this will be released shortly after the holidays.

**Pull request merged**
