### PR TITLE
feat: Add support for custom backoff

### LINKED ISSUE #452: onRetryAttempt is not awaited / custom back off strategy
Even though in the documentation it's stated that onRetryAttempt can return a promise,
the promise is not awaited:
see https://github.com/googleapis/gaxios/blob/bf6afebe9bb50261d0aed5ae128853f977682773/src/common.ts#L147
and https://github.com/googleapis/gaxios/blob/bf6afebe9bb50261d0aed5ae128853f977682773/src/retry.ts#L79

My challenge is to build a custom retry handler, which checks for retry-after headers and so on.. 
I see that adding await would maybe change some behaviour for end-users.. so I would instead vote for a property that allows to override the default expoenitial back off handler? Would that be an option? I can prepare a PR in this case.

### PR DESCRIPTION
**Pull request by camflan**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com//issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #452  🦕

### CODE REVIEW

**Comment by ddelgrosso1** [comment]
Hi @camflan thank you for the PR. Can you update the commit message to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by camflan** [comment]
> Hi @camflan thank you for the PR. Can you update the commit message to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

done! sorry for the delay

**Comment by camflan** [comment]
@ddelgrosso1 I think this is ready to run CI workflows

**Comment by camflan** [comment]
@ddelgrosso1 Ready to go

**Comment by ddelgrosso1** [comment]
Thanks @camflan, apologies on the delay. Will get this merged today.

**Comment by camflan** [comment]
> Thanks @camflan, apologies on the delay. Will get this merged today. Can you run `npm run fix` to fix the linter issues?

Awesome, thanks! Pushed fix for formatting just now

**Comment by ddelgrosso1** [comment]
Thanks again for the contribution @camflan!

**Review by ddelgrosso1 — APPROVED** [review]

**Pull request merged**
